<?xml version="1.0" encoding="UTF-8"?>
<com.ibm.datatools.etl.errmsgs:Message xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:com.ibm.datatools.etl.errmsgs="http:///com/ibm/datatools/etl/errmsgs.ecore" msgNum="12209" timestamp="1516334640781" msgTxt="Validation succeeded for the 'l1q1p2' flow. However, there were warnings." msgSeverity="WARN" component="dataflow.validation" msgDescTxt="Validation succeeded for l1q1p2 with warnings." msgCause="" msgResponse="" entityType="DataFlow">
  <expandedMsgs msgNum="12208" timestamp="1516334640781" msgTxt="Validation succeeded for the 'flowLabel'." msgSeverity="LOG" component="dataflow.validation" msgDescTxt="Validation succeeded for flowLabel." msgCause="" msgResponse="" entityType="DataFlow" operatorID="01"/>
  <expandedMsgs msgNum="12208" timestamp="1516334640781" msgTxt="Validation succeeded for the 'flowLabel'." msgSeverity="LOG" component="dataflow.validation" msgDescTxt="Validation succeeded for flowLabel." msgCause="" msgResponse="" entityType="DataFlow" operatorID="03"/>
  <expandedMsgs msgNum="12208" timestamp="1516334640781" msgTxt="Validation succeeded for the 'flowLabel'." msgSeverity="LOG" component="dataflow.validation" msgDescTxt="Validation succeeded for flowLabel." msgCause="" msgResponse="" entityType="DataFlow" operatorID="04">
    <expandedMsgs msgNum="1253" timestamp="1516334640781" msgTxt="Operator 'class': Error on condition 'SQL_?ColumnRefUnresolved : Unable to find table for column &quot;313&quot;.'" msgSeverity="WARN" component="dataflow.core" msgDescTxt="Attempting to parse condition with the SQL parser generated an error. " msgCause="A problem was encountered while parsing the condition. " msgResponse="Correct the condition." entityType="MSG_CONDITION_PARSE" operatorID="04"/>
  </expandedMsgs>
  <expandedMsgs msgNum="12208" timestamp="1516334640781" msgTxt="Validation succeeded for the 'flowLabel'." msgSeverity="LOG" component="dataflow.validation" msgDescTxt="Validation succeeded for flowLabel." msgCause="" msgResponse="" entityType="DataFlow" operatorID="022"/>
  <expandedMsgs msgNum="12208" timestamp="1516334640781" msgTxt="Validation succeeded for the 'flowLabel'." msgSeverity="LOG" component="dataflow.validation" msgDescTxt="Validation succeeded for flowLabel." msgCause="" msgResponse="" entityType="DataFlow" operatorID="023"/>
  <expandedMsgs msgNum="12208" timestamp="1516334640781" msgTxt="Validation succeeded for the 'flowLabel'." msgSeverity="LOG" component="dataflow.validation" msgDescTxt="Validation succeeded for flowLabel." msgCause="" msgResponse="" entityType="DataFlow" operatorID="026"/>
  <expandedMsgs msgNum="12208" timestamp="1516334640781" msgTxt="Validation succeeded for the 'flowLabel'." msgSeverity="LOG" component="dataflow.validation" msgDescTxt="Validation succeeded for flowLabel." msgCause="" msgResponse="" entityType="DataFlow" operatorID="028"/>
</com.ibm.datatools.etl.errmsgs:Message>
