<?xml version="1.0" encoding="UTF-8"?>
<com.ibm.datatools.etl.errmsgs:Message xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:com.ibm.datatools.etl.errmsgs="http:///com/ibm/datatools/etl/errmsgs.ecore" msgNum="12208" timestamp="1516332802289" msgTxt="Validation succeeded for the 'l2p1'." msgSeverity="LOG" component="dataflow.validation" msgDescTxt="Validation succeeded for l2p1." msgCause="" msgResponse="" entityType="DataFlow">
  <expandedMsgs msgNum="12208" timestamp="1516332802289" msgTxt="Validation succeeded for the 'flowLabel'." msgSeverity="LOG" component="dataflow.validation" msgDescTxt="Validation succeeded for flowLabel." msgCause="" msgResponse="" entityType="DataFlow" operatorID="01"/>
  <expandedMsgs msgNum="12208" timestamp="1516332802289" msgTxt="Validation succeeded for the 'flowLabel'." msgSeverity="LOG" component="dataflow.validation" msgDescTxt="Validation succeeded for flowLabel." msgCause="" msgResponse="" entityType="DataFlow" operatorID="010"/>
  <expandedMsgs msgNum="12208" timestamp="1516332802304" msgTxt="Validation succeeded for the 'flowLabel'." msgSeverity="LOG" component="dataflow.validation" msgDescTxt="Validation succeeded for flowLabel." msgCause="" msgResponse="" entityType="DataFlow" operatorID="013"/>
</com.ibm.datatools.etl.errmsgs:Message>
